name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Force HTTPS for Git submodules
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: haloooloolo
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:rocketwatch"
          push: true
          tags: haloooloolo/rocketwatch:latest
          no-cache: true
          platforms: linux/amd64

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
